services:
  postgres:
    image: postgres:17-alpine
    container_name: my-postgres-17
    restart: always
    environment:
      POSTGRES_USER: autogen_pln
      POSTGRES_PASSWORD: 1221425pg
      POSTGRES_DB: autogen_prod
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  web:
    image: ludyhasby/autogen-be-worker:1.1.0
    entrypoint: ["/app/web"]
    container_name: autogen-be-web
    restart: always
    ports:
      - "9004:9004"
    environment:
      TZ: Asia/Jakarta
    env_file:
      - .env.production
    volumes:
      - ./file:/app/file
      - ./.env.production:/app/.env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  worker:
    image: ludyhasby/autogen-be-worker:1.1.0
    entrypoint: ["/app/worker"]
    container_name: autogen-be-worker
    restart: always
    environment:
      TZ: Asia/Jakarta
    env_file:
      - .env.production
    volumes:
      - ./file:/app/file # Menggunakan path relatif agar portable
      - ./.env.production:/app/.env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge